name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build Windows
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller regex_assistant.spec --clean
        
    - name: Build macOS
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller regex_assistant_mac.spec --clean
        
    - name: Build Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller regex_assistant_linux.spec --clean
        
    - name: Create Release
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/RegexAIAssistant.exe
          dist/RegexAIAssistant.app
          dist/RegexAIAssistant
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: |
          # Regex AI Assistant ${{ github.ref_name }}
          
          ## Features
          - 🤖 AI-powered regex pattern generation
          - 🎯 Extract specific values from text using natural language
          - 💻 Modern, dark-themed user interface
          - 📋 One-click copy to clipboard
          - 🔒 Secure API key management
          
          ## Requirements
          - Windows 10/11, macOS 10.15+, or Linux
          - GROQ API key (required for AI functionality)
          
          ## Installation
          1. Download the appropriate file for your platform:
             - Windows: `RegexAIAssistant.exe`
             - macOS: `RegexAIAssistant.app`
             - Linux: `RegexAIAssistant`
          2. Run the application
          3. Enter your GROQ API key when prompted
          
          ## How to Use
          1. Enter your sample text in the "Sample Text" field
          2. Specify the target value you want to extract
          3. Click "Generate Regex" to create the pattern
          4. Use "Copy to Clipboard" to copy the generated regex
          
          ## First Run
          On first launch, you'll be prompted to enter your GROQ API key. This key is required for the AI functionality and is stored securely in a local .env file.
          
          ## Notes
          - The application is completely self-contained - no Python installation required
          - All dependencies are bundled with the executable
          - Your API key is stored locally and never shared
          
          ## Support
          If you encounter any issues or have questions, please open an issue on the GitHub repository.
          
          ---
          *Built with Python, PyQt5, and GROQ AI*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 